# Generated by Django 3.1.3 on 2020-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_pic',
            field=models.ImageField(blank=True, null=True, upload_to='dt_pics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True),
        ),
    ]
