# Generated by Django 3.1.3 on 2020-12-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20201203_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='web_link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
